import { Disease, Symptom, Drug, Examination, BodyPart, Department, Relation } from './schema.js'

export const DISEASES: Disease[] = [
  {
    id: 'D001',
    name: '肺结节',
    aliases: ['肺部结节', '肺内结节', 'pulmonary nodule'],
    symptoms: ['咳嗽', '胸痛', '咯血', '呼吸困难', '发热', '乏力'],
    departments: ['呼吸内科', '胸外科', '肿瘤科'],
    description: '肺结节是指肺内直径小于或等于3厘米的类圆形或不规则形病灶，影像学表现为密度增高的阴影，可单发或多发，边界清晰或不清晰。',
    causes: ['吸烟', '空气污染', '职业暴露', '肺部感染史', '肺结核病史', '真菌感染'],
    prevention: ['戒烟', '避免二手烟', '减少空气污染暴露', '定期体检', '职业防护'],
    complications: ['肺癌', '肺部感染', '呼吸功能下降'],
    icdCode: 'R91'
  },
  {
    id: 'D002',
    name: '肺癌',
    aliases: ['原发性支气管肺癌', '支气管肺癌', 'lung cancer', 'bronchogenic carcinoma'],
    symptoms: ['咳嗽', '咯血', '胸痛', '呼吸困难', '声音嘶哑', '体重下降', '食欲减退', '发热', '乏力', '杵状指'],
    departments: ['胸外科', '肿瘤科', '呼吸内科', '放疗科'],
    description: '肺癌是起源于肺部支气管黏膜或腺体的恶性肿瘤，是最常见的肺部原发性恶性肿瘤，发病率和死亡率居全球癌症首位。',
    causes: ['吸烟', '二手烟', '空气污染', '职业暴露', '遗传因素', '肺部慢性疾病', '放射线暴露'],
    prevention: ['戒烟', '避免二手烟', '减少空气污染暴露', '职业防护', '定期筛查', '健康饮食', '适量运动'],
    complications: ['胸腔积液', '上腔静脉综合征', '骨转移', '脑转移', '肝转移', '恶病质'],
    icdCode: 'C34'
  },
  {
    id: 'D003',
    name: '肺炎',
    aliases: ['肺部感染', 'pneumonia'],
    symptoms: ['发热', '咳嗽', '咳痰', '胸痛', '呼吸困难', '乏力', '食欲减退', '头痛', '肌肉酸痛'],
    departments: ['呼吸内科', '感染科', '急诊科'],
    description: '肺炎是指终末气道、肺泡和肺间质的炎症，可由细菌、病毒、真菌、寄生虫等致病微生物，以及放射线、化学物质等因素引起。',
    causes: ['细菌感染', '病毒感染', '真菌感染', '支原体感染', '衣原体感染', '吸入性因素', '免疫力下降'],
    prevention: ['接种疫苗', '勤洗手', '避免接触患者', '增强免疫力', '戒烟', '避免过度疲劳'],
    complications: ['肺脓肿', '胸腔积液', '脓胸', '呼吸衰竭', '败血症', '感染性休克'],
    icdCode: 'J18'
  },
  {
    id: 'D004',
    name: '慢性阻塞性肺疾病',
    aliases: ['慢阻肺', 'COPD', 'chronic obstructive pulmonary disease'],
    symptoms: ['慢性咳嗽', '咳痰', '呼吸困难', '喘息', '胸闷', '体重下降', '肌肉萎缩', '乏力'],
    departments: ['呼吸内科', '老年科'],
    description: '慢性阻塞性肺疾病是一种具有气流阻塞特征的慢性支气管炎和（或）肺气肿，可进一步发展为肺心病和呼吸衰竭的常见慢性疾病。',
    causes: ['吸烟', '空气污染', '职业粉尘', '化学物质暴露', '遗传因素', '呼吸道感染', '社会经济地位低'],
    prevention: ['戒烟', '避免空气污染', '职业防护', '预防呼吸道感染', '肺功能锻炼', '营养支持'],
    complications: ['肺心病', '呼吸衰竭', '自发性气胸', '慢性呼吸衰竭', '肺动脉高压'],
    icdCode: 'J44'
  },
  {
    id: 'D005',
    name: '支气管哮喘',
    aliases: ['哮喘', 'asthma', '支气管痉挛'],
    symptoms: ['喘息', '呼吸困难', '胸闷', '咳嗽', '夜间症状加重', '运动后症状加重'],
    departments: ['呼吸内科', '变态反应科', '儿科'],
    description: '支气管哮喘是由多种细胞和细胞组分参与的气道慢性炎症性疾病，这种慢性炎症导致气道高反应性，通常出现广泛多变的可逆性气流受限。',
    causes: ['遗传因素', '过敏原', '空气污染', '呼吸道感染', '运动', '药物', '情绪因素', '冷空气'],
    prevention: ['避免过敏原', '规范用药', '定期复查', '戒烟', '避免空气污染', '预防呼吸道感染', '适度运动'],
    complications: ['气胸', '肺不张', '呼吸衰竭', '肺心病', '生长发育迟缓'],
    icdCode: 'J45'
  },
  {
    id: 'D006',
    name: '肺结核',
    aliases: ['结核病', 'TB', 'pulmonary tuberculosis'],
    symptoms: ['咳嗽', '咳痰', '咯血', '胸痛', '发热', '盗汗', '乏力', '体重下降', '食欲减退'],
    departments: ['感染科', '呼吸内科', '结核病科'],
    description: '肺结核是由结核分枝杆菌引起的肺部感染性疾病，是结核病中最常见的一种，主要通过呼吸道传播。',
    causes: ['结核分枝杆菌感染', '免疫力下降', '营养不良', '糖尿病', 'HIV感染', '长期使用免疫抑制剂'],
    prevention: ['接种卡介苗', '避免接触患者', '增强免疫力', '改善营养', '早期发现早期治疗', '规范用药'],
    complications: ['咯血', '自发性气胸', '脓胸', '肺心病', '呼吸衰竭', '结核性脑膜炎'],
    icdCode: 'A15'
  },
  {
    id: 'D007',
    name: '肺栓塞',
    aliases: ['肺动脉栓塞', 'PE', 'pulmonary embolism'],
    symptoms: ['呼吸困难', '胸痛', '咯血', '晕厥', '心悸', '烦躁不安', '出冷汗', '血压下降'],
    departments: ['呼吸内科', '心血管内科', '急诊科'],
    description: '肺栓塞是以各种栓子阻塞肺动脉或其分支为其发病原因的一组疾病或临床综合征的总称，包括肺血栓栓塞症、脂肪栓塞综合征等。',
    causes: ['深静脉血栓', '长期卧床', '手术', '创伤', '恶性肿瘤', '妊娠', '口服避孕药', '遗传性易栓症'],
    prevention: ['早期活动', '抗凝预防', '穿弹力袜', '避免长期卧床', '控制危险因素', '定期复查'],
    complications: ['肺梗死', '肺动脉高压', '右心衰竭', '死亡'],
    icdCode: 'I26'
  },
  {
    id: 'D008',
    name: '肺气肿',
    aliases: ['肺过度充气', 'emphysema'],
    symptoms: ['呼吸困难', '咳嗽', '咳痰', '乏力', '体重下降', '桶状胸'],
    departments: ['呼吸内科', '胸外科'],
    description: '肺气肿是指终末细支气管远端的气腔异常持久扩张，并伴有肺泡壁破坏，而无明显的纤维化，是慢性阻塞性肺疾病的一种表现。',
    causes: ['吸烟', '空气污染', '职业暴露', '遗传因素', '反复肺部感染', 'α1-抗胰蛋白酶缺乏'],
    prevention: ['戒烟', '避免空气污染', '职业防护', '预防感染', '肺功能锻炼', '营养支持'],
    complications: ['呼吸衰竭', '肺心病', '自发性气胸', '肺部感染'],
    icdCode: 'J43'
  },
  {
    id: 'D009',
    name: '支气管扩张',
    aliases: ['支扩', 'bronchiectasis'],
    symptoms: ['慢性咳嗽', '咳大量脓痰', '咯血', '反复肺部感染', '呼吸困难', '杵状指'],
    departments: ['呼吸内科', '胸外科'],
    description: '支气管扩张是指支气管及其周围肺组织慢性炎症导致的支气管壁肌肉和弹性组织破坏，管腔形成不可逆性扩张、变形。',
    causes: ['肺部感染', '肺结核', '免疫缺陷', '遗传因素', '气道阻塞', '吸入有毒气体', '自身免疫性疾病'],
    prevention: ['预防和治疗肺部感染', '戒烟', '避免空气污染', '增强免疫力', '定期复查', '疫苗接种'],
    complications: ['大咯血', '呼吸衰竭', '肺心病', '脓胸', '脑脓肿'],
    icdCode: 'J47'
  },
  {
    id: 'D010',
    name: '肺纤维化',
    aliases: ['特发性肺纤维化', 'IPF', 'pulmonary fibrosis'],
    symptoms: ['进行性呼吸困难', '干咳', '乏力', '体重下降', '杵状指', '发绀'],
    departments: ['呼吸内科', '风湿免疫科'],
    description: '肺纤维化是以成纤维细胞增殖及大量细胞外基质聚集并伴炎症损伤、组织结构破坏为特征的一大类肺疾病的终末期表现。',
    causes: ['特发性', '自身免疫性疾病', '药物毒性', '职业暴露', '放射治疗', '慢性感染', '遗传因素'],
    prevention: ['避免职业暴露', '戒烟', '预防感染', '规范用药', '定期复查', '肺康复训练'],
    complications: ['呼吸衰竭', '肺动脉高压', '肺心病', '肺癌'],
    icdCode: 'J84'
  },
  {
    id: 'D011',
    name: '胸腔积液',
    aliases: ['胸水', 'pleural effusion'],
    symptoms: ['呼吸困难', '胸痛', '咳嗽', '发热', '乏力', '食欲减退'],
    departments: ['呼吸内科', '胸外科'],
    description: '胸腔积液是指胸膜腔内液体的异常积聚，正常情况下胸膜腔内有少量液体起润滑作用，当液体产生过多或吸收减少时即形成胸腔积液。',
    causes: ['心力衰竭', '肺炎', '肺结核', '恶性肿瘤', '肺栓塞', '肝硬化', '肾病综合征', '低蛋白血症'],
    prevention: ['治疗原发病', '定期体检', '控制心功能', '预防感染', '营养支持'],
    complications: ['呼吸困难加重', '肺不张', '感染', '胸膜肥厚'],
    icdCode: 'J90'
  },
  {
    id: 'D012',
    name: '气胸',
    aliases: ['肺萎陷', 'pneumothorax'],
    symptoms: ['突发胸痛', '呼吸困难', '咳嗽', '心悸', '烦躁不安', '发绀'],
    departments: ['呼吸内科', '胸外科', '急诊科'],
    description: '气胸是指气体进入胸膜腔，造成积气状态，导致肺组织受压萎陷，可分为自发性气胸、外伤性气胸和医源性气胸。',
    causes: ['肺大疱破裂', '胸部外伤', '机械通气', '肺部疾病', '剧烈运动', '用力屏气', '慢性阻塞性肺疾病'],
    prevention: ['避免剧烈运动', '戒烟', '治疗肺部基础疾病', '避免用力屏气', '定期体检'],
    complications: ['张力性气胸', '呼吸衰竭', '休克', '感染'],
    icdCode: 'J93'
  },
  {
    id: 'D013',
    name: '肺脓肿',
    aliases: ['肺化脓症', 'lung abscess'],
    symptoms: ['高热', '咳嗽', '咳大量脓臭痰', '胸痛', '呼吸困难', '咯血', '乏力', '体重下降'],
    departments: ['呼吸内科', '感染科', '胸外科'],
    description: '肺脓肿是由多种病原菌引起的肺部化脓性感染，早期为肺组织的感染性炎症，继而坏死、液化，形成脓肿。',
    causes: ['吸入性因素', '血源性感染', '继发性感染', '免疫力下降', '口腔卫生差', '酗酒', '癫痫发作'],
    prevention: ['保持口腔卫生', '避免误吸', '增强免疫力', '及时治疗肺部感染', '戒烟戒酒'],
    complications: ['脓胸', '支气管胸膜瘘', '大咯血', '肺坏疽', '转移性脓肿'],
    icdCode: 'J85'
  },
  {
    id: 'D014',
    name: '肺动脉高压',
    aliases: ['PAH', 'pulmonary arterial hypertension'],
    symptoms: ['呼吸困难', '乏力', '胸痛', '晕厥', '心悸', '下肢水肿', '腹水', '咯血'],
    departments: ['心血管内科', '呼吸内科'],
    description: '肺动脉高压是指肺动脉压力升高超过一定界值的一种血流动力学和病理生理状态，可导致右心衰竭。',
    causes: ['特发性', '遗传性', '结缔组织病', '先天性心脏病', '门脉高压', 'HIV感染', '药物毒性', '慢性血栓栓塞'],
    prevention: ['早期诊断治疗', '避免高危因素', '定期复查', '规范用药', '避免妊娠', '避免高海拔'],
    complications: ['右心衰竭', '心律失常', '血栓形成', '咯血', '死亡'],
    icdCode: 'I27'
  },
  {
    id: 'D015',
    name: '小细胞肺癌',
    aliases: ['SCLC', '燕麦细胞癌', 'small cell lung cancer'],
    symptoms: ['咳嗽', '咯血', '胸痛', '呼吸困难', '声音嘶哑', '上腔静脉综合征', '体重下降', '乏力', '神经内分泌症状'],
    departments: ['肿瘤科', '胸外科', '放疗科', '呼吸内科'],
    description: '小细胞肺癌是肺癌的一种病理类型，约占肺癌总数的15%，恶性程度高，增殖快，易早期转移，对化疗和放疗敏感。',
    causes: ['吸烟', '职业暴露', '空气污染', '遗传因素', '放射线暴露'],
    prevention: ['戒烟', '避免职业暴露', '减少空气污染暴露', '定期筛查', '健康生活方式'],
    complications: ['上腔静脉综合征', '脑转移', '骨转移', '肝转移', '副肿瘤综合征', '恶病质'],
    icdCode: 'C34'
  },
  {
    id: 'D016',
    name: '非小细胞肺癌',
    aliases: ['NSCLC', 'non-small cell lung cancer'],
    symptoms: ['咳嗽', '咯血', '胸痛', '呼吸困难', '声音嘶哑', '体重下降', '乏力', '吞咽困难'],
    departments: ['胸外科', '肿瘤科', '放疗科', '呼吸内科'],
    description: '非小细胞肺癌是肺癌的主要类型，约占肺癌总数的85%，包括腺癌、鳞癌、大细胞癌等，治疗以手术为主，辅以放化疗和靶向治疗。',
    causes: ['吸烟', '二手烟', '职业暴露', '空气污染', '遗传因素', '肺部慢性疾病'],
    prevention: ['戒烟', '避免二手烟', '职业防护', '减少空气污染暴露', '定期筛查', '健康饮食'],
    complications: ['胸腔积液', '骨转移', '脑转移', '肝转移', '上腔静脉综合征', '恶病质'],
    icdCode: 'C34'
  },
  {
    id: 'D017',
    name: '肺腺癌',
    aliases: ['腺癌', 'lung adenocarcinoma'],
    symptoms: ['咳嗽', '咯血', '胸痛', '呼吸困难', '体重下降', '乏力', '骨痛', '头痛'],
    departments: ['胸外科', '肿瘤科', '呼吸内科'],
    description: '肺腺癌是非小细胞肺癌的一种，是目前最常见的肺癌类型，多发生于肺周边，易发生远处转移，女性和非吸烟者多见。',
    causes: ['吸烟', '二手烟', '空气污染', '职业暴露', '遗传因素', '基因突变'],
    prevention: ['戒烟', '避免二手烟', '减少空气污染暴露', '职业防护', '定期筛查', '基因检测'],
    complications: ['胸腔积液', '骨转移', '脑转移', '肝转移', '心包积液', '恶病质'],
    icdCode: 'C34'
  },
  {
    id: 'D018',
    name: '肺鳞癌',
    aliases: ['鳞状细胞癌', 'lung squamous cell carcinoma'],
    symptoms: ['咳嗽', '咯血', '胸痛', '呼吸困难', '发热', '体重下降', '乏力'],
    departments: ['胸外科', '肿瘤科', '呼吸内科'],
    description: '肺鳞癌是非小细胞肺癌的一种，多发生于段以上支气管，与吸烟关系密切，男性多见，生长较慢，转移较晚。',
    causes: ['吸烟', '职业暴露', '空气污染', '慢性支气管炎', '遗传因素'],
    prevention: ['戒烟', '职业防护', '减少空气污染暴露', '治疗慢性支气管炎', '定期筛查'],
    complications: ['阻塞性肺炎', '肺不张', '大咯血', '支气管阻塞', '胸腔积液'],
    icdCode: 'C34'
  },
  {
    id: 'D019',
    name: '急性呼吸窘迫综合征',
    aliases: ['ARDS', 'acute respiratory distress syndrome'],
    symptoms: ['进行性呼吸困难', '发绀', '烦躁不安', '低氧血症', '呼吸急促', '心动过速'],
    departments: ['重症医学科', '呼吸内科', '急诊科'],
    description: '急性呼吸窘迫综合征是一种以进行性呼吸困难和顽固性低氧血症为特征的急性呼吸衰竭，病死率高。',
    causes: ['肺炎', '脓毒症', '创伤', '胃内容物吸入', '胰腺炎', '大量输血', '脂肪栓塞', '药物中毒'],
    prevention: ['及时治疗原发病', '预防感染', '避免误吸', '合理输液', '早期识别高危患者'],
    complications: ['多器官功能衰竭', '呼吸机相关性肺炎', '气胸', '肺纤维化', '死亡'],
    icdCode: 'J80'
  },
  {
    id: 'D020',
    name: '睡眠呼吸暂停综合征',
    aliases: ['阻塞性睡眠呼吸暂停', 'OSA', 'obstructive sleep apnea'],
    symptoms: ['打鼾', '睡眠中呼吸暂停', '白天嗜睡', '晨起头痛', '记忆力下降', '注意力不集中', '夜尿增多', '性功能减退'],
    departments: ['呼吸内科', '耳鼻喉科', '睡眠中心'],
    description: '睡眠呼吸暂停综合征是指睡眠时上气道反复塌陷、阻塞引起呼吸暂停和低通气，导致间歇性低氧血症和睡眠结构紊乱。',
    causes: ['肥胖', '上气道解剖异常', '饮酒', '镇静药物', '甲状腺功能减退', '肢端肥大症', '遗传因素'],
    prevention: ['控制体重', '戒烟戒酒', '避免镇静药物', '侧卧睡眠', '治疗鼻部疾病', '定期复查'],
    complications: ['高血压', '冠心病', '心律失常', '脑卒中', '糖尿病', '肺动脉高压', '交通事故'],
    icdCode: 'G47'
  },
  {
    id: 'D021',
    name: '肺曲霉病',
    aliases: ['曲霉菌感染', 'pulmonary aspergillosis'],
    symptoms: ['咳嗽', '咯血', '胸痛', '呼吸困难', '发热', '乏力', '体重下降'],
    departments: ['呼吸内科', '感染科'],
    description: '肺曲霉病是由曲霉菌引起的肺部感染性疾病，可分为过敏性、寄生性和侵袭性三种类型，免疫力低下者易患。',
    causes: ['曲霉菌感染', '免疫力下降', '长期使用免疫抑制剂', '慢性肺部疾病', '中性粒细胞减少'],
    prevention: ['避免接触曲霉菌', '增强免疫力', '合理使用免疫抑制剂', '预防性抗真菌治疗', '改善环境'],
    complications: ['大咯血', '播散性感染', '呼吸衰竭', '肺脓肿'],
    icdCode: 'B44'
  },
  {
    id: 'D022',
    name: '肺隐球菌病',
    aliases: ['隐球菌感染', 'pulmonary cryptococcosis'],
    symptoms: ['咳嗽', '胸痛', '发热', '乏力', '体重下降', '呼吸困难', '头痛'],
    departments: ['呼吸内科', '感染科'],
    description: '肺隐球菌病是由新型隐球菌引起的肺部感染，可单独存在或与中枢神经系统隐球菌病同时存在，免疫力低下者易患。',
    causes: ['新型隐球菌感染', '免疫力下降', 'HIV感染', '长期使用免疫抑制剂', '糖尿病', '恶性肿瘤'],
    prevention: ['避免接触鸽粪', '增强免疫力', '合理使用免疫抑制剂', 'HIV感染者预防用药', '定期体检'],
    complications: ['隐球菌脑膜炎', '播散性感染', '呼吸衰竭', '胸腔积液'],
    icdCode: 'B45'
  },
  {
    id: 'D023',
    name: '肺包虫病',
    aliases: ['棘球蚴病', 'pulmonary echinococcosis'],
    symptoms: ['咳嗽', '胸痛', '呼吸困难', '咯血', '发热', '过敏反应'],
    departments: ['呼吸内科', '胸外科', '感染科'],
    description: '肺包虫病是由细粒棘球绦虫的幼虫感染引起的寄生虫病，多见于牧区，可形成肺内囊肿。',
    causes: ['细粒棘球绦虫感染', '接触犬类', '食用被虫卵污染的食物或水', '牧区生活'],
    prevention: ['避免接触犬类', '注意饮食卫生', '牧区防护', '定期体检', '犬类驱虫'],
    complications: ['囊肿破裂', '过敏性休克', '继发感染', '支气管胸膜瘘'],
    icdCode: 'B67'
  },
  {
    id: 'D024',
    name: '肺吸虫病',
    aliases: ['并殖吸虫病', 'paragonimiasis'],
    symptoms: ['咳嗽', '咳铁锈色痰', '胸痛', '呼吸困难', '发热', '乏力', '腹痛', '皮下结节'],
    departments: ['呼吸内科', '感染科'],
    description: '肺吸虫病是由并殖吸虫引起的寄生虫病，因生食或半生食含有囊蚴的淡水蟹或蝲蛄而感染。',
    causes: ['并殖吸虫感染', '生食淡水蟹', '生食蝲蛄', '饮用生水'],
    prevention: ['避免生食淡水蟹和蝲蛄', '不饮用生水', '加强粪便管理', '健康教育'],
    complications: ['胸腔积液', '气胸', '脑型肺吸虫病', '皮下结节'],
    icdCode: 'B66'
  },
  {
    id: 'D025',
    name: '肺错构瘤',
    aliases: ['肺良性肿瘤', 'pulmonary hamartoma'],
    symptoms: ['咳嗽', '胸痛', '呼吸困难', '多数无症状'],
    departments: ['胸外科', '呼吸内科'],
    description: '肺错构瘤是肺部最常见的良性肿瘤，由正常肺组织成分异常组合而成，多发生于肺周边，生长缓慢。',
    causes: ['发育异常', '先天性因素'],
    prevention: ['定期体检', '早期发现'],
    complications: ['极少数可恶变', '压迫症状'],
    icdCode: 'D14'
  },
  {
    id: 'D026',
    name: '肺炎球菌肺炎',
    aliases: ['大叶性肺炎', 'pneumococcal pneumonia'],
    symptoms: ['高热', '寒战', '咳嗽', '咳铁锈色痰', '胸痛', '呼吸困难', '口唇疱疹'],
    departments: ['呼吸内科', '感染科', '急诊科'],
    description: '肺炎球菌肺炎是由肺炎链球菌引起的肺部急性炎症，是最常见的社区获得性肺炎之一，好发于青壮年。',
    causes: ['肺炎链球菌感染', '免疫力下降', '受凉', '疲劳', '酗酒', '慢性疾病'],
    prevention: ['接种肺炎疫苗', '避免受凉', '增强免疫力', '戒烟戒酒', '避免过度疲劳'],
    complications: ['胸腔积液', '脓胸', '肺脓肿', '脑膜炎', '心包炎', '败血症'],
    icdCode: 'J13'
  },
  {
    id: 'D027',
    name: '支原体肺炎',
    aliases: ['原发性非典型肺炎', 'mycoplasma pneumonia'],
    symptoms: ['发热', '咳嗽', '头痛', '乏力', '咽痛', '肌肉酸痛', '食欲减退'],
    departments: ['呼吸内科', '感染科', '儿科'],
    description: '支原体肺炎是由肺炎支原体引起的肺部急性炎症，是社区获得性肺炎的常见类型，好发于儿童和青少年。',
    causes: ['肺炎支原体感染', '密切接触传播', '免疫力下降'],
    prevention: ['避免密切接触患者', '勤洗手', '戴口罩', '增强免疫力', '保持室内通风'],
    complications: ['胸腔积液', '心肌炎', '脑炎', '溶血性贫血', '皮疹'],
    icdCode: 'J15'
  },
  {
    id: 'D028',
    name: '病毒性肺炎',
    aliases: ['病毒性肺部感染', 'viral pneumonia'],
    symptoms: ['发热', '干咳', '乏力', '头痛', '肌肉酸痛', '呼吸困难', '咽痛', '流涕'],
    departments: ['呼吸内科', '感染科', '急诊科'],
    description: '病毒性肺炎是由病毒感染引起的肺部炎症，常见病原体包括流感病毒、腺病毒、呼吸道合胞病毒、新型冠状病毒等。',
    causes: ['病毒感染', '免疫力下降', '密切接触传播', '季节因素'],
    prevention: ['接种疫苗', '勤洗手', '戴口罩', '避免人群聚集', '保持社交距离', '增强免疫力'],
    complications: ['继发细菌感染', '呼吸衰竭', 'ARDS', '心肌炎', '多器官功能衰竭'],
    icdCode: 'J12'
  },
  {
    id: 'D029',
    name: '吸入性肺炎',
    aliases: ['吸入性肺部感染', 'aspiration pneumonia'],
    symptoms: ['发热', '咳嗽', '咳痰', '呼吸困难', '胸痛', '发绀', '意识障碍'],
    departments: ['呼吸内科', '老年科', '急诊科'],
    description: '吸入性肺炎是指吸入食物、胃内容物或其他刺激性物质引起的肺部炎症，多见于意识障碍、吞咽困难的患者。',
    causes: ['意识障碍', '吞咽困难', '胃食管反流', '气管切开', '鼻饲', '麻醉后', '酗酒'],
    prevention: ['预防误吸', '抬高床头', '评估吞咽功能', '口腔护理', '及时清理口腔分泌物'],
    complications: ['肺脓肿', '脓胸', '呼吸衰竭', 'ARDS', '死亡'],
    icdCode: 'J69'
  },
  {
    id: 'D030',
    name: '间质性肺病',
    aliases: ['间质性肺炎', 'ILD', 'interstitial lung disease'],
    symptoms: ['进行性呼吸困难', '干咳', '乏力', '体重下降', '杵状指', '发绀'],
    departments: ['呼吸内科', '风湿免疫科'],
    description: '间质性肺病是一组以肺间质炎症和纤维化为特征的疾病群，包括特发性肺纤维化、结缔组织病相关肺病等。',
    causes: ['特发性', '结缔组织病', '药物毒性', '职业暴露', '放射治疗', '感染', '遗传因素'],
    prevention: ['避免职业暴露', '戒烟', '预防感染', '规范用药', '定期复查', '肺康复训练'],
    complications: ['呼吸衰竭', '肺动脉高压', '肺心病', '肺癌'],
    icdCode: 'J84'
  }
]

export const SYMPTOMS: Symptom[] = [
  { id: 'S001', name: '咳嗽', aliases: ['咳', 'cough'], relatedBodyParts: ['肺', '支气管', '气管'], severityLevel: 'moderate', description: '咳嗽是呼吸系统最常见的症状之一，是机体的一种保护性反射动作，通过咳嗽可以清除呼吸道分泌物和异物。', possibleDiseases: ['肺结节', '肺癌', '肺炎', '慢性阻塞性肺疾病', '支气管哮喘', '肺结核', '支气管扩张'] },
  { id: 'S002', name: '咯血', aliases: ['咳血', 'hemoptysis'], relatedBodyParts: ['肺', '支气管'], severityLevel: 'severe', description: '咯血是指喉部以下的呼吸道出血，经咳嗽动作从口腔排出，是呼吸系统疾病的严重症状。', possibleDiseases: ['肺癌', '肺结核', '支气管扩张', '肺栓塞', '肺脓肿', '肺炎'] },
  { id: 'S003', name: '呼吸困难', aliases: ['气促', '气短', 'dyspnea'], relatedBodyParts: ['肺', '心脏'], severityLevel: 'severe', description: '呼吸困难是指患者主观上感觉空气不足、呼吸费力，客观上表现为呼吸频率、节律和深度的改变。', possibleDiseases: ['慢性阻塞性肺疾病', '肺癌', '肺栓塞', '肺纤维化', '支气管哮喘', '肺炎', '胸腔积液', '气胸'] },
  { id: 'S004', name: '胸痛', aliases: ['胸部疼痛', 'chest pain'], relatedBodyParts: ['肺', '胸膜', '心脏'], severityLevel: 'moderate', description: '胸痛是指胸部区域的疼痛感觉，可由胸壁、呼吸系统、心血管系统、消化系统等疾病引起。', possibleDiseases: ['肺癌', '肺栓塞', '肺炎', '气胸', '胸膜炎', '肺结核', '胸腔积液'] },
  { id: 'S005', name: '发热', aliases: ['发烧', 'fever'], relatedBodyParts: ['全身'], severityLevel: 'moderate', description: '发热是指体温升高超过正常范围，是机体对致病因子的一种全身性防御反应。', possibleDiseases: ['肺炎', '肺结核', '肺脓肿', '肺癌', '肺栓塞', '支气管扩张'] },
  { id: 'S006', name: '咳痰', aliases: ['痰多', 'expectoration'], relatedBodyParts: ['肺', '支气管'], severityLevel: 'mild', description: '咳痰是指通过咳嗽动作将呼吸道分泌物排出口腔，痰液的性质、颜色、量对诊断有重要意义。', possibleDiseases: ['慢性阻塞性肺疾病', '肺炎', '支气管扩张', '肺脓肿', '肺结核', '支气管炎'] },
  { id: 'S007', name: '喘息', aliases: ['喘鸣', 'wheezing'], relatedBodyParts: ['支气管', '肺'], severityLevel: 'moderate', description: '喘息是指呼吸时出现的高调哮鸣音，是由于气流通过狭窄的气道时产生的湍流所致。', possibleDiseases: ['支气管哮喘', '慢性阻塞性肺疾病', '肺癌', '支气管异物', '心力衰竭'] },
  { id: 'S008', name: '乏力', aliases: ['疲劳', '无力', 'fatigue'], relatedBodyParts: ['全身'], severityLevel: 'mild', description: '乏力是指全身疲乏无力，是许多疾病的非特异性症状，可由多种原因引起。', possibleDiseases: ['肺癌', '肺结核', '慢性阻塞性肺疾病', '肺纤维化', '肺炎', '贫血'] },
  { id: 'S009', name: '体重下降', aliases: ['消瘦', 'weight loss'], relatedBodyParts: ['全身'], severityLevel: 'moderate', description: '体重下降是指非自愿性的体重减轻，是许多慢性疾病和恶性肿瘤的常见症状。', possibleDiseases: ['肺癌', '肺结核', '慢性阻塞性肺疾病', '肺纤维化', '肺脓肿'] },
  { id: 'S010', name: '盗汗', aliases: ['夜间出汗', 'night sweat'], relatedBodyParts: ['全身'], severityLevel: 'mild', description: '盗汗是指入睡后出汗，醒来后汗止，是结核病的典型症状之一。', possibleDiseases: ['肺结核', '肺癌', '淋巴瘤', '感染性疾病'] },
  { id: 'S011', name: '声音嘶哑', aliases: ['声嘶', 'hoarseness'], relatedBodyParts: ['喉', '声带'], severityLevel: 'moderate', description: '声音嘶哑是指声音变得粗糙、沙哑，可由喉部疾病或神经损伤引起。', possibleDiseases: ['肺癌', '喉癌', '甲状腺癌', '声带息肉', '喉炎'] },
  { id: 'S012', name: '杵状指', aliases: ['鼓槌指', 'clubbing'], relatedBodyParts: ['手指', '脚趾'], severityLevel: 'mild', description: '杵状指是指手指末端增生、肥厚，呈杵状膨大，是慢性缺氧的表现之一。', possibleDiseases: ['肺癌', '支气管扩张', '肺脓肿', '肺纤维化', '先天性心脏病'] },
  { id: 'S013', name: '发绀', aliases: ['紫绀', 'cyanosis'], relatedBodyParts: ['皮肤', '黏膜'], severityLevel: 'severe', description: '发绀是指皮肤和黏膜呈青紫色，是由于血液中还原血红蛋白增多所致，提示缺氧。', possibleDiseases: ['慢性阻塞性肺疾病', '肺纤维化', '肺栓塞', '先天性心脏病', '呼吸衰竭'] },
  { id: 'S014', name: '晕厥', aliases: ['昏厥', 'syncope'], relatedBodyParts: ['脑', '心脏'], severityLevel: 'severe', description: '晕厥是指一过性的意识丧失，可由心血管、神经、代谢等多种原因引起。', possibleDiseases: ['肺栓塞', '肺动脉高压', '心律失常', '心肌梗死', '脑卒中'] },
  { id: 'S015', name: '下肢水肿', aliases: ['脚肿', 'leg edema'], relatedBodyParts: ['下肢'], severityLevel: 'moderate', description: '下肢水肿是指下肢组织间隙液体积聚，可由心脏、肝脏、肾脏疾病等引起。', possibleDiseases: ['肺动脉高压', '肺心病', '心力衰竭', '肝硬化', '肾病综合征'] },
  { id: 'S016', name: '食欲减退', aliases: ['纳差', '厌食', 'anorexia'], relatedBodyParts: ['消化系统'], severityLevel: 'mild', description: '食欲减退是指对食物缺乏欲望，是许多疾病的非特异性症状。', possibleDiseases: ['肺癌', '肺结核', '慢性阻塞性肺疾病', '肺炎', '消化系统疾病'] },
  { id: 'S017', name: '头痛', aliases: ['头疼', 'headache'], relatedBodyParts: ['头部'], severityLevel: 'mild', description: '头痛是指头部疼痛，可由多种原因引起，包括原发性头痛和继发性头痛。', possibleDiseases: ['肺炎', '肺结核', '肺癌脑转移', '高血压', '脑膜炎'] },
  { id: 'S018', name: '肌肉酸痛', aliases: ['肌痛', 'myalgia'], relatedBodyParts: ['肌肉'], severityLevel: 'mild', description: '肌肉酸痛是指肌肉疼痛不适，可由运动、感染、自身免疫病等引起。', possibleDiseases: ['肺炎', '流感', '病毒性肺炎', '肌炎', '横纹肌溶解'] },
  { id: 'S019', name: '心悸', aliases: ['心慌', 'palpitation'], relatedBodyParts: ['心脏'], severityLevel: 'moderate', description: '心悸是指自觉心跳加快、加强或不规则，可由心脏疾病或非心脏因素引起。', possibleDiseases: ['肺栓塞', '肺动脉高压', '肺心病', '心律失常', '甲状腺功能亢进'] },
  { id: 'S020', name: '烦躁不安', aliases: ['焦虑', 'agitation'], relatedBodyParts: ['神经系统'], severityLevel: 'moderate', description: '烦躁不安是指情绪不稳定、坐立不安，可由缺氧、疼痛、焦虑症等引起。', possibleDiseases: ['肺栓塞', '呼吸衰竭', 'ARDS', '低氧血症'] },
  { id: 'S021', name: '打鼾', aliases: ['鼾声', 'snoring'], relatedBodyParts: ['上气道'], severityLevel: 'mild', description: '打鼾是指睡眠时气流通过狭窄的上气道时产生的振动声音，是睡眠呼吸暂停的主要表现。', possibleDiseases: ['睡眠呼吸暂停综合征', '肥胖', '鼻中隔偏曲', '扁桃体肥大'] },
  { id: 'S022', name: '白天嗜睡', aliases: ['日间困倦', 'excessive daytime sleepiness'], relatedBodyParts: ['神经系统'], severityLevel: 'moderate', description: '白天嗜睡是指白天过度困倦、想睡觉，影响日常活动和工作。', possibleDiseases: ['睡眠呼吸暂停综合征', '发作性睡病', '抑郁症', '睡眠不足'] },
  { id: 'S023', name: '晨起头痛', aliases: ['早晨头痛', 'morning headache'], relatedBodyParts: ['头部'], severityLevel: 'mild', description: '晨起头痛是指早晨醒来时出现的头痛，可能与睡眠质量差、缺氧有关。', possibleDiseases: ['睡眠呼吸暂停综合征', '高血压', '睡眠不足', '颈椎病'] },
  { id: 'S024', name: '记忆力下降', aliases: ['健忘', 'memory loss'], relatedBodyParts: ['脑'], severityLevel: 'mild', description: '记忆力下降是指记忆能力减退，可由多种原因引起，包括缺氧、睡眠障碍等。', possibleDiseases: ['睡眠呼吸暂停综合征', '慢性阻塞性肺疾病', '阿尔茨海默病', '抑郁症'] },
  { id: 'S025', name: '夜尿增多', aliases: ['夜间多尿', 'nocturia'], relatedBodyParts: ['泌尿系统'], severityLevel: 'mild', description: '夜尿增多是指夜间排尿次数增多，可由多种原因引起。', possibleDiseases: ['睡眠呼吸暂停综合征', '心力衰竭', '前列腺增生', '糖尿病'] },
  { id: 'S026', name: '吞咽困难', aliases: ['吞咽障碍', 'dysphagia'], relatedBodyParts: ['食管', '咽喉'], severityLevel: 'moderate', description: '吞咽困难是指吞咽时感觉困难或疼痛，可由食管疾病或神经系统疾病引起。', possibleDiseases: ['肺癌', '食管癌', '脑卒中', '重症肌无力', '食管炎'] },
  { id: 'S027', name: '上腔静脉综合征', aliases: ['上腔静脉压迫', 'superior vena cava syndrome'], relatedBodyParts: ['上腔静脉'], severityLevel: 'severe', description: '上腔静脉综合征是由于上腔静脉受压或阻塞引起的头颈部静脉回流障碍。', possibleDiseases: ['肺癌', '淋巴瘤', '纵隔肿瘤', '血栓形成'] },
  { id: 'S028', name: '骨痛', aliases: ['骨骼疼痛', 'bone pain'], relatedBodyParts: ['骨骼'], severityLevel: 'moderate', description: '骨痛是指骨骼疼痛，可由外伤、感染、肿瘤骨转移等引起。', possibleDiseases: ['肺癌骨转移', '多发性骨髓瘤', '骨肿瘤', '骨质疏松'] },
  { id: 'S029', name: '胸膜摩擦音', aliases: ['胸膜摩擦', 'pleural friction rub'], relatedBodyParts: ['胸膜'], severityLevel: 'moderate', description: '胸膜摩擦音是胸膜炎症时，两层胸膜相互摩擦产生的声音。', possibleDiseases: ['胸膜炎', '肺炎', '肺栓塞', '肺结核'] },
  { id: 'S030', name: '桶状胸', aliases: ['肺气肿胸', 'barrel chest'], relatedBodyParts: ['胸廓'], severityLevel: 'mild', description: '桶状胸是指胸廓前后径增大，呈圆桶状，是肺气肿的典型体征。', possibleDiseases: ['肺气肿', '慢性阻塞性肺疾病', '支气管哮喘'] }
]

export const DRUGS: Drug[] = [
  {
    id: 'DR001',
    name: '奥希替尼',
    genericName: 'Osimertinib',
    aliases: ['泰瑞沙', 'AZD9291'],
    category: 'other',
    indications: ['EGFR突变阳性的非小细胞肺癌', 'EGFR T790M突变阳性的非小细胞肺癌'],
    contraindications: ['对奥希替尼过敏者', '妊娠期', '哺乳期'],
    dosage: { adult: '80mg', frequency: '每日一次', maxDose: '80mg/日' },
    sideEffects: ['腹泻', '皮疹', '恶心', '食欲减退', '口腔炎', '甲沟炎', '间质性肺病', 'QT间期延长'],
    interactions: ['强CYP3A4诱导剂', '强CYP3A4抑制剂'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20180016'
  },
  {
    id: 'DR002',
    name: '吉非替尼',
    genericName: 'Gefitinib',
    aliases: ['易瑞沙', 'Iressa'],
    category: 'other',
    indications: ['EGFR突变阳性的非小细胞肺癌'],
    contraindications: ['对吉非替尼过敏者', '妊娠期', '哺乳期'],
    dosage: { adult: '250mg', frequency: '每日一次', maxDose: '250mg/日' },
    sideEffects: ['腹泻', '皮疹', '瘙痒', '痤疮', '恶心', '呕吐', '食欲减退', '间质性肺病'],
    interactions: ['CYP3A4诱导剂', 'CYP3A4抑制剂', '华法林'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20140142'
  },
  {
    id: 'DR003',
    name: '厄洛替尼',
    genericName: 'Erlotinib',
    aliases: ['特罗凯', 'Tarceva'],
    category: 'other',
    indications: ['EGFR突变阳性的非小细胞肺癌', '胰腺癌'],
    contraindications: ['对厄洛替尼过敏者', '妊娠期', '哺乳期'],
    dosage: { adult: '150mg', frequency: '每日一次', maxDose: '150mg/日' },
    sideEffects: ['皮疹', '腹泻', '食欲减退', '恶心', '呕吐', '疲劳', '间质性肺病', '角膜炎'],
    interactions: ['CYP3A4诱导剂', 'CYP3A4抑制剂', '华法林', '质子泵抑制剂'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20060394'
  },
  {
    id: 'DR004',
    name: '阿来替尼',
    genericName: 'Alectinib',
    aliases: ['安圣莎', 'Alecensa'],
    category: 'other',
    indications: ['ALK阳性的非小细胞肺癌'],
    contraindications: ['对阿来替尼过敏者', '妊娠期', '哺乳期'],
    dosage: { adult: '600mg', frequency: '每日两次', maxDose: '1200mg/日' },
    sideEffects: ['便秘', '水肿', '肌痛', '恶心', '皮疹', '肝功能异常', '间质性肺病', '心动过缓'],
    interactions: ['CYP3A4诱导剂', 'CYP3A4抑制剂'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20190032'
  },
  {
    id: 'DR005',
    name: '克唑替尼',
    genericName: 'Crizotinib',
    aliases: ['赛可瑞', 'Xalkori'],
    category: 'other',
    indications: ['ALK阳性的非小细胞肺癌', 'ROS1阳性的非小细胞肺癌'],
    contraindications: ['对克唑替尼过敏者', '妊娠期', '哺乳期'],
    dosage: { adult: '250mg', frequency: '每日两次', maxDose: '500mg/日' },
    sideEffects: ['恶心', '腹泻', '呕吐', '水肿', '便秘', '视力障碍', '头晕', '肝功能异常', '间质性肺病'],
    interactions: ['CYP3A4诱导剂', 'CYP3A4抑制剂', 'CYP2B6底物'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20130068'
  },
  {
    id: 'DR006',
    name: '索托拉西布',
    genericName: 'Sotorasib',
    aliases: ['Lumakras'],
    category: 'other',
    indications: ['KRAS G12C突变的非小细胞肺癌'],
    contraindications: ['对索托拉西布过敏者', '妊娠期', '哺乳期'],
    dosage: { adult: '960mg', frequency: '每日一次', maxDose: '960mg/日' },
    sideEffects: ['腹泻', '肌肉骨骼疼痛', '恶心', '疲劳', '肝功能异常', '咳嗽'],
    interactions: ['CYP3A4诱导剂', 'CYP3A4抑制剂', 'P-gp抑制剂'],
    storage: '室温保存',
    otc: false,
    approvalNumber: 'FDA批准'
  },
  {
    id: 'DR007',
    name: '帕博利珠单抗',
    genericName: 'Pembrolizumab',
    aliases: ['可瑞达', 'Keytruda'],
    category: 'other',
    indications: ['PD-L1高表达的非小细胞肺癌', '黑色素瘤', '头颈部鳞癌', '经典型霍奇金淋巴瘤'],
    contraindications: ['对帕博利珠单抗过敏者', '妊娠期', '哺乳期'],
    dosage: { adult: '200mg', frequency: '每3周一次', maxDose: '200mg/次' },
    sideEffects: ['疲劳', '瘙痒', '腹泻', '皮疹', '关节痛', '甲状腺功能减退', '肺炎', '肝炎', '结肠炎'],
    interactions: ['免疫抑制剂'],
    storage: '2-8°C冷藏',
    otc: false,
    approvalNumber: '国药准字S20180019'
  },
  {
    id: 'DR008',
    name: '阿莫西林',
    genericName: 'Amoxicillin',
    aliases: ['阿莫仙', 'Amoxil'],
    category: 'antibiotic',
    indications: ['肺炎', '支气管炎', '中耳炎', '鼻窦炎', '尿路感染', '皮肤软组织感染'],
    contraindications: ['青霉素过敏者', '传染性单核细胞增多症'],
    dosage: { adult: '0.5-1g', frequency: '每6-8小时一次', maxDose: '4g/日' },
    sideEffects: ['恶心', '呕吐', '腹泻', '皮疹', '过敏反应', '伪膜性肠炎'],
    interactions: ['丙磺舒', '口服避孕药', '抗凝药'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H31020363'
  },
  {
    id: 'DR009',
    name: '阿奇霉素',
    genericName: 'Azithromycin',
    aliases: ['希舒美', 'Zithromax'],
    category: 'antibiotic',
    indications: ['支原体肺炎', '衣原体感染', '社区获得性肺炎', '急性支气管炎', '咽炎', '扁桃体炎'],
    contraindications: ['大环内酯类过敏者', '肝功能严重损害者'],
    dosage: { adult: '0.5g', frequency: '每日一次', maxDose: '0.5g/日' },
    sideEffects: ['恶心', '呕吐', '腹泻', '腹痛', '头痛', '头晕', 'QT间期延长'],
    interactions: ['抗酸药', '华法林', '环孢素', '地高辛'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20093779'
  },
  {
    id: 'DR010',
    name: '左氧氟沙星',
    genericName: 'Levofloxacin',
    aliases: ['利复星', 'Levaquin'],
    category: 'antibiotic',
    indications: ['社区获得性肺炎', '医院获得性肺炎', '慢性支气管炎急性发作', '尿路感染', '皮肤软组织感染'],
    contraindications: ['喹诺酮类过敏者', '癫痫患者', '妊娠期', '哺乳期', '18岁以下患者'],
    dosage: { adult: '0.5g', frequency: '每日一次', maxDose: '0.75g/日' },
    sideEffects: ['恶心', '呕吐', '腹泻', '头痛', '头晕', '失眠', '肌腱炎', 'QT间期延长', '光敏反应'],
    interactions: ['抗酸药', '华法林', '环孢素', '非甾体抗炎药', '降糖药'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20040091'
  },
  {
    id: 'DR011',
    name: '沙丁胺醇',
    genericName: 'Salbutamol',
    aliases: ['万托林', 'Ventolin'],
    category: 'respiratory',
    indications: ['支气管哮喘', '慢性阻塞性肺疾病', '可逆性气道阻塞'],
    contraindications: ['对沙丁胺醇过敏者'],
    dosage: { adult: '100-200μg', frequency: '按需使用', maxDose: '800μg/日' },
    sideEffects: ['心悸', '震颤', '头痛', '恶心', '低钾血症', '心律失常'],
    interactions: ['β受体阻滞剂', '单胺氧化酶抑制剂', '三环类抗抑郁药', '洋地黄类'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H37020544'
  },
  {
    id: 'DR012',
    name: '布地奈德',
    genericName: 'Budesonide',
    aliases: ['普米克', 'Pulmicort'],
    category: 'respiratory',
    indications: ['支气管哮喘', '慢性阻塞性肺疾病', '过敏性鼻炎'],
    contraindications: ['对布地奈德过敏者', '活动性肺结核'],
    dosage: { adult: '200-800μg', frequency: '每日两次', maxDose: '1600μg/日' },
    sideEffects: ['口腔念珠菌感染', '声音嘶哑', '咳嗽', '头痛', '恶心'],
    interactions: ['酮康唑', '伊曲康唑', '利托那韦'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20030410'
  },
  {
    id: 'DR013',
    name: '噻托溴铵',
    genericName: 'Tiotropium',
    aliases: ['思力华', 'Spiriva'],
    category: 'respiratory',
    indications: ['慢性阻塞性肺疾病', '支气管哮喘'],
    contraindications: ['对噻托溴铵或阿托品衍生物过敏者'],
    dosage: { adult: '18μg', frequency: '每日一次', maxDose: '18μg/日' },
    sideEffects: ['口干', '便秘', '心悸', '排尿困难', '视力模糊', '头痛'],
    interactions: ['抗胆碱能药物'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20060453'
  },
  {
    id: 'DR014',
    name: '异丙托溴铵',
    genericName: 'Ipratropium',
    aliases: ['爱全乐', 'Atrovent'],
    category: 'respiratory',
    indications: ['慢性阻塞性肺疾病', '支气管哮喘', '急性支气管痉挛'],
    contraindications: ['对异丙托溴铵或阿托品衍生物过敏者'],
    dosage: { adult: '40-80μg', frequency: '每日3-4次', maxDose: '320μg/日' },
    sideEffects: ['口干', '头痛', '咳嗽', '恶心', '视力模糊', '心悸'],
    interactions: ['抗胆碱能药物', 'β受体激动剂'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20050295'
  },
  {
    id: 'DR015',
    name: '氨茶碱',
    genericName: 'Aminophylline',
    aliases: ['茶碱', 'Theophylline'],
    category: 'respiratory',
    indications: ['支气管哮喘', '慢性阻塞性肺疾病', '心源性哮喘'],
    contraindications: ['对茶碱过敏者', '活动性消化性溃疡', '未控制的癫痫'],
    dosage: { adult: '0.1-0.2g', frequency: '每日3次', maxDose: '1g/日' },
    sideEffects: ['恶心', '呕吐', '心悸', '失眠', '头痛', '震颤', '心律失常', '癫痫发作'],
    interactions: ['西咪替丁', '红霉素', '环丙沙星', '苯妥英钠', '利福平', '吸烟'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H31022659'
  },
  {
    id: 'DR016',
    name: '异烟肼',
    genericName: 'Isoniazid',
    aliases: ['雷米封', 'INH'],
    category: 'antibiotic',
    indications: ['肺结核', '结核性脑膜炎', '结核病预防'],
    contraindications: ['对异烟肼过敏者', '急性肝病', '既往异烟肼相关肝损伤'],
    dosage: { adult: '5mg/kg', frequency: '每日一次', maxDose: '300mg/日' },
    sideEffects: ['肝毒性', '周围神经炎', '恶心', '呕吐', '皮疹', '发热', '关节痛'],
    interactions: ['苯妥英钠', '卡马西平', '华法林', '茶碱', '环丝氨酸'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H31020593'
  },
  {
    id: 'DR017',
    name: '利福平',
    genericName: 'Rifampicin',
    aliases: ['RFP'],
    category: 'antibiotic',
    indications: ['肺结核', '麻风病', '其他敏感菌感染'],
    contraindications: ['对利福平过敏者', '严重肝功能损害', '妊娠早期'],
    dosage: { adult: '10mg/kg', frequency: '每日一次', maxDose: '600mg/日' },
    sideEffects: ['肝毒性', '胃肠道反应', '皮疹', '发热', '流感样症状', '血小板减少', '溶血性贫血'],
    interactions: ['华法林', '口服避孕药', '糖皮质激素', '环孢素', '地高辛', '抗糖尿病药'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H31020436'
  },
  {
    id: 'DR018', 
    name: '乙胺丁醇',
    genericName: 'Ethambutol',
    aliases: ['EMB'],
    category: 'antibiotic',
    indications: ['肺结核', '结核性脑膜炎'],
    contraindications: ['对乙胺丁醇过敏者', '视神经炎', '色盲', '6岁以下儿童'],
    dosage: { adult: '15-25mg/kg', frequency: '每日一次', maxDose: '2.5g/日' },
    sideEffects: ['视神经炎', '视力下降', '色觉障碍', '胃肠道反应', '头痛', '关节痛'],
    interactions: ['含铝抗酸药'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H31022111'
  },
  {
    id: 'DR019',
    name: '吡嗪酰胺',
    genericName: 'Pyrazinamide',
    aliases: ['PZA'],
    category: 'antibiotic',
    indications: ['肺结核', '结核性脑膜炎'],
    contraindications: ['对吡嗪酰胺过敏者', '严重肝功能损害', '急性痛风'],
    dosage: { adult: '15-30mg/kg', frequency: '每日一次', maxDose: '2g/日' },
    sideEffects: ['肝毒性', '高尿酸血症', '痛风', '胃肠道反应', '皮疹', '关节痛'],
    interactions: ['别嘌醇', '丙磺舒'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H31020839'
  },
  {
    id: 'DR020',
    name: '低分子肝素',
    genericName: 'Enoxaparin',
    aliases: ['克赛', 'Lovenox'],
    category: 'cardiovascular',
    indications: ['肺栓塞', '深静脉血栓', '预防血栓形成', '急性冠脉综合征'],
    contraindications: ['对肝素过敏者', '活动性出血', '血小板减少症', '严重高血压'],
    dosage: { adult: '1mg/kg', frequency: '每12小时一次', maxDose: '2mg/kg/日' },
    sideEffects: ['出血', '血小板减少', '过敏反应', '注射部位血肿', '骨质疏松'],
    interactions: ['抗凝药', '抗血小板药', '非甾体抗炎药'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字J20180031'
  },
  {
    id: 'DR021',
    name: '华法林',
    genericName: 'Warfarin',
    aliases: ['Coumadin'],
    category: 'cardiovascular',
    indications: ['肺栓塞', '深静脉血栓', '房颤', '心脏瓣膜置换术后'],
    contraindications: ['对华法林过敏者', '活动性出血', '严重高血压', '妊娠期', '严重肝肾功能损害'],
    dosage: { adult: '2.5-5mg', frequency: '每日一次', maxDose: '根据INR调整' },
    sideEffects: ['出血', '皮肤坏死', '紫趾综合征', '过敏反应'],
    interactions: ['阿司匹林', '非甾体抗炎药', '抗生素', '抗真菌药', '质子泵抑制剂', '维生素K'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H31022166'
  },
  {
    id: 'DR022',
    name: '氨溴索',
    genericName: 'Ambroxol',
    aliases: ['沐舒坦', 'Mucosolvan'],
    category: 'respiratory',
    indications: ['急性支气管炎', '慢性支气管炎', '肺炎', '支气管扩张', '肺结核'],
    contraindications: ['对氨溴索过敏者', '妊娠早期'],
    dosage: { adult: '30mg', frequency: '每日3次', maxDose: '120mg/日' },
    sideEffects: ['恶心', '呕吐', '腹泻', '皮疹', '头痛'],
    interactions: ['抗生素（增加抗生素在肺组织中的浓度）'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20030392'
  },
  {
    id: 'DR023',
    name: '乙酰半胱氨酸',
    genericName: 'Acetylcysteine',
    aliases: ['富露施', 'Fluimucil'],
    category: 'respiratory',
    indications: ['急性支气管炎', '慢性支气管炎', '肺炎', '肺脓肿', '对乙酰氨基酚中毒'],
    contraindications: ['对乙酰半胱氨酸过敏者', '严重哮喘发作'],
    dosage: { adult: '600mg', frequency: '每日1-2次', maxDose: '1200mg/日' },
    sideEffects: ['恶心', '呕吐', '腹泻', '口腔炎', '皮疹', '支气管痉挛'],
    interactions: ['硝酸甘油', '活性炭'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20057188'
  },
  {
    id: 'DR024',
    name: '右美沙芬',
    genericName: 'Dextromethorphan',
    aliases: ['美沙芬'],
    category: 'respiratory',
    indications: ['干咳', '感冒引起的咳嗽', '支气管炎引起的咳嗽'],
    contraindications: ['对右美沙芬过敏者', '痰多患者', '妊娠期', '哺乳期'],
    dosage: { adult: '15-30mg', frequency: '每日3-4次', maxDose: '120mg/日' },
    sideEffects: ['头晕', '嗜睡', '恶心', '呕吐', '便秘'],
    interactions: ['单胺氧化酶抑制剂', '中枢抑制药'],
    storage: '室温保存',
    otc: true,
    approvalNumber: '国药准字H19990216'
  },
  {
    id: 'DR025',
    name: '复方甘草片',
    genericName: 'Compound Liquorice Tablets',
    aliases: ['甘草片'],
    category: 'respiratory',
    indications: ['咳嗽', '咳痰'],
    contraindications: ['对甘草过敏者', '高血压', '水肿', '妊娠期', '哺乳期'],
    dosage: { adult: '2-3片', frequency: '每日3次', maxDose: '9片/日' },
    sideEffects: ['水肿', '高血压', '低钾血症', '恶心', '呕吐'],
    interactions: ['利尿剂', '洋地黄类', '降压药'],
    storage: '室温保存',
    otc: true,
    approvalNumber: '国药准字H31022602'
  },
  {
    id: 'DR026',
    name: '氟康唑',
    genericName: 'Fluconazole',
    aliases: ['大扶康', 'Diflucan'],
    category: 'antibiotic',
    indications: ['肺曲霉病', '肺隐球菌病', '念珠菌感染', '隐球菌脑膜炎'],
    contraindications: ['对氟康唑过敏者', '同时使用特非那定', '妊娠期'],
    dosage: { adult: '200-400mg', frequency: '每日一次', maxDose: '800mg/日' },
    sideEffects: ['恶心', '呕吐', '腹泻', '头痛', '皮疹', '肝功能异常', 'QT间期延长'],
    interactions: ['华法林', '环孢素', '苯妥英钠', '口服降糖药', '利福平'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20023358'
  },
  {
    id: 'DR027',
    name: '伏立康唑',
    genericName: 'Voriconazole',
    aliases: ['威凡', 'Vfend'],
    category: 'antibiotic',
    indications: ['侵袭性曲霉病', '肺曲霉病', '念珠菌感染', '隐球菌感染'],
    contraindications: ['对伏立康唑过敏者', '同时使用西沙必利', '妊娠期', '哺乳期'],
    dosage: { adult: '200mg', frequency: '每日两次', maxDose: '400mg/日' },
    sideEffects: ['视力障碍', '皮疹', '恶心', '呕吐', '腹泻', '头痛', '肝功能异常', '光敏反应'],
    interactions: ['西沙必利', '特非那定', '阿司咪唑', '奎尼丁', '环孢素', '华法林', '苯妥英钠'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20055751'
  },
  {
    id: 'DR028',
    name: '两性霉素B',
    genericName: 'Amphotericin B',
    aliases: ['锋弛欣', 'Fungizone'],
    category: 'antibiotic',
    indications: ['侵袭性曲霉病', '肺隐球菌病', '念珠菌感染', '毛霉菌病'],
    contraindications: ['对两性霉素B过敏者'],
    dosage: { adult: '0.5-1mg/kg', frequency: '每日一次', maxDose: '1.5mg/kg/日' },
    sideEffects: ['发热', '寒战', '肾功能损害', '低钾血症', '贫血', '恶心', '呕吐', '静脉炎'],
    interactions: ['氨基糖苷类', '环孢素', '糖皮质激素', '洋地黄类'],
    storage: '2-8°C冷藏',
    otc: false,
    approvalNumber: '国药准字H31022668'
  },
  {
    id: 'DR029',
    name: '泼尼松',
    genericName: 'Prednisone',
    aliases: ['强的松', 'Prednisone'],
    category: 'other',
    indications: ['支气管哮喘', '间质性肺病', '自身免疫性疾病', '过敏性疾病'],
    contraindications: ['活动性消化性溃疡', '严重高血压', '糖尿病', '精神病', '妊娠早期'],
    dosage: { adult: '5-60mg', frequency: '每日一次', maxDose: '根据病情调整' },
    sideEffects: ['满月脸', '水牛背', '体重增加', '血糖升高', '血压升高', '骨质疏松', '消化性溃疡', '感染风险增加'],
    interactions: ['非甾体抗炎药', '华法林', '口服降糖药', '利尿剂', '洋地黄类'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H31020656'
  },
  {
    id: 'DR030',
    name: '甲泼尼龙',
    genericName: 'Methylprednisolone',
    aliases: ['美卓乐', 'Medrol'],
    category: 'other',
    indications: ['支气管哮喘急性发作', '间质性肺病', '自身免疫性疾病', '过敏性疾病'],
    contraindications: ['活动性消化性溃疡', '严重高血压', '糖尿病', '精神病', '妊娠早期'],
    dosage: { adult: '4-48mg', frequency: '每日一次', maxDose: '根据病情调整' },
    sideEffects: ['满月脸', '水牛背', '体重增加', '血糖升高', '血压升高', '骨质疏松', '消化性溃疡', '感染风险增加'],
    interactions: ['非甾体抗炎药', '华法林', '口服降糖药', '利尿剂', '洋地黄类', '红霉素'],
    storage: '室温保存',
    otc: false,
    approvalNumber: '国药准字H20070174'
  }
]

export const EXAMINATIONS: Examination[] = [
  {
    id: 'E001',
    name: '胸部CT',
    aliases: ['肺部CT', 'Chest CT'],
    category: 'imaging',
    normalRange: [{ unit: '描述性', description: '肺实质无异常密度影，气管支气管通畅，纵隔无肿大淋巴结' }],
    clinicalSignificance: '用于诊断肺结节、肺癌、肺炎、肺结核、支气管扩张等肺部疾病，是肺部疾病诊断的重要影像学检查。',
    preparationRequired: ['去除金属物品', '空腹（增强CT）'],
    relatedDiseases: ['肺结节', '肺癌', '肺炎', '肺结核', '支气管扩张', '肺纤维化', '肺栓塞']
  },
  {
    id: 'E002',
    name: '胸部X线',
    aliases: ['胸片', 'Chest X-ray'],
    category: 'imaging',
    normalRange: [{ unit: '描述性', description: '肺野清晰，心影大小形态正常，膈肌光滑' }],
    clinicalSignificance: '用于筛查肺部疾病，如肺炎、肺结核、肺癌、气胸等，是呼吸系统疾病的初步检查。',
    preparationRequired: ['去除金属物品', '穿宽松衣物'],
    relatedDiseases: ['肺炎', '肺结核', '肺癌', '气胸', '胸腔积液', '慢性阻塞性肺疾病']
  },
  {
    id: 'E003',
    name: '肺功能检查',
    aliases: ['肺功能测定', 'Pulmonary Function Test'],
    category: 'other',
    normalRange: [
      { min: 80, max: 120, unit: '%预计值', description: 'FEV1/FVC ≥70%' }
    ],
    clinicalSignificance: '用于评估肺通气功能和换气功能，诊断慢性阻塞性肺疾病、支气管哮喘等疾病，评估疾病严重程度和治疗效果。',
    preparationRequired: ['检查前避免剧烈运动', '检查前避免吸烟', '避免使用支气管扩张剂（检查前4-6小时）'],
    relatedDiseases: ['慢性阻塞性肺疾病', '支气管哮喘', '肺纤维化', '肺气肿']
  },
  {
    id: 'E004',
    name: '支气管镜检查',
    aliases: ['纤维支气管镜', 'Bronchoscopy'],
    category: 'other',
    normalRange: [{ unit: '描述性', description: '气管支气管黏膜正常，管腔通畅，无新生物' }],
    clinicalSignificance: '用于诊断肺癌、支气管内膜结核、支气管异物等，可进行活检、刷检、灌洗等操作获取病理标本。',
    preparationRequired: ['空腹6-8小时', '签署知情同意书', '检查前禁烟'],
    relatedDiseases: ['肺癌', '支气管内膜结核', '支气管异物', '支气管扩张', '肺脓肿']
  },
  {
    id: 'E005',
    name: '痰培养',
    aliases: ['痰细菌培养', 'Sputum Culture'],
    category: 'other',
    normalRange: [{ unit: '描述性', description: '正常菌群生长或无致病菌生长' }],
    clinicalSignificance: '用于诊断肺部感染性疾病，明确病原菌，指导抗生素选择。',
    preparationRequired: ['晨起清水漱口', '深咳留取痰液', '避免唾液污染'],
    relatedDiseases: ['肺炎', '肺结核', '肺脓肿', '支气管扩张']
  },
  {
    id: 'E006',
    name: '痰脱落细胞学检查',
    aliases: ['痰细胞学检查', 'Sputum Cytology'],
    category: 'other',
    normalRange: [{ unit: '描述性', description: '未见恶性肿瘤细胞' }],
    clinicalSignificance: '用于筛查肺癌，特别是中央型肺癌，可发现早期肺癌细胞。',
    preparationRequired: ['晨起深咳留取痰液', '连续3天送检'],
    relatedDiseases: ['肺癌', '支气管肺癌']
  },
  {
    id: 'E007',
    name: '血气分析',
    aliases: ['动脉血气', 'Blood Gas Analysis'],
    category: 'blood',
    normalRange: [
      { min: 7.35, max: 7.45, unit: 'pH', description: '酸碱度' },
      { min: 35, max: 45, unit: 'mmHg', description: 'PaCO2' },
      { min: 80, max: 100, unit: 'mmHg', description: 'PaO2' },
      { min: 22, max: 27, unit: 'mmol/L', description: 'HCO3-' }
    ],
    clinicalSignificance: '用于评估肺换气功能和酸碱平衡状态，诊断呼吸衰竭、酸碱失衡等。',
    preparationRequired: ['避免剧烈运动', '避免情绪激动'],
    relatedDiseases: ['呼吸衰竭', '慢性阻塞性肺疾病', '肺栓塞', 'ARDS', '肺纤维化']
  },
  {
    id: 'E008',
    name: 'D-二聚体',
    aliases: ['D-dimer'],
    category: 'blood',
    normalRange: [
      { min: 0, max: 0.5, unit: 'mg/L', description: '正常参考值' }
    ],
    clinicalSignificance: '用于排除肺栓塞和深静脉血栓，D-二聚体升高提示可能存在血栓形成。',
    preparationRequired: ['空腹'],
    relatedDiseases: ['肺栓塞', '深静脉血栓', 'DIC', '肺结核', '肺癌']
  },
  {
    id: 'E009',
    name: '癌胚抗原',
    aliases: ['CEA'],
    category: 'tumor_marker',
    normalRange: [
      { min: 0, max: 5, unit: 'ng/mL', description: '正常参考值（吸烟者可稍高）' }
    ],
    clinicalSignificance: '用于肺癌辅助诊断和疗效监测，特别是肺腺癌，CEA升高提示可能存在肺癌。',
    preparationRequired: ['空腹'],
    relatedDiseases: ['肺癌', '肺腺癌', '结直肠癌', '胃癌']
  },
  {
    id: 'E010',
    name: '神经元特异性烯醇化酶',
    aliases: ['NSE'],
    category: 'tumor_marker',
    normalRange: [
      { min: 0, max: 16.3, unit: 'ng/mL', description: '正常参考值' }
    ],
    clinicalSignificance: '用于小细胞肺癌的诊断和疗效监测，NSE升高提示可能存在小细胞肺癌。',
    preparationRequired: ['空腹'],
    relatedDiseases: ['小细胞肺癌', '神经内分泌肿瘤']
  },
  {
    id: 'E011',
    name: '细胞角蛋白19片段',
    aliases: ['CYFRA21-1'],
    category: 'tumor_marker',
    normalRange: [
      { min: 0, max: 3.3, unit: 'ng/mL', description: '正常参考值' }
    ],
    clinicalSignificance: '用于非小细胞肺癌的诊断和疗效监测，特别是肺鳞癌，CYFRA21-1升高提示可能存在肺癌。',
    preparationRequired: ['空腹'],
    relatedDiseases: ['非小细胞肺癌', '肺鳞癌']
  },
  {
    id: 'E012',
    name: '低剂量CT筛查',
    aliases: ['LDCT', 'Low-dose CT'],
    category: 'imaging',
    normalRange: [{ unit: '描述性', description: '无肺结节或肺结节<6mm' }],
    clinicalSignificance: '用于高危人群肺癌筛查，可早期发现肺结节和早期肺癌，降低肺癌死亡率。',
    preparationRequired: ['去除金属物品'],
    relatedDiseases: ['肺结节', '肺癌', '早期肺癌筛查']
  }
]

export const BODY_PARTS: BodyPart[] = [
  { id: 'BP001', name: '肺', system: 'respiratory', relatedSymptoms: ['咳嗽', '呼吸困难', '胸痛', '咯血', '喘息'] },
  { id: 'BP002', name: '支气管', system: 'respiratory', relatedSymptoms: ['咳嗽', '喘息', '咳痰', '呼吸困难'] },
  { id: 'BP003', name: '气管', system: 'respiratory', relatedSymptoms: ['咳嗽', '呼吸困难', '喘息'] },
  { id: 'BP004', name: '胸膜', system: 'respiratory', relatedSymptoms: ['胸痛', '呼吸困难', '胸膜摩擦音'] },
  { id: 'BP005', name: '纵隔', system: 'respiratory', relatedSymptoms: ['胸痛', '呼吸困难', '上腔静脉综合征'] },
  { id: 'BP006', name: '心脏', system: 'cardiovascular', relatedSymptoms: ['心悸', '胸痛', '呼吸困难', '下肢水肿'] },
  { id: 'BP007', name: '上腔静脉', system: 'cardiovascular', relatedSymptoms: ['上腔静脉综合征', '面部水肿', '颈静脉怒张'] },
  { id: 'BP008', name: '肺动脉', system: 'cardiovascular', relatedSymptoms: ['呼吸困难', '胸痛', '咯血', '晕厥'] },
  { id: 'BP009', name: '喉', system: 'respiratory', relatedSymptoms: ['声音嘶哑', '咳嗽', '呼吸困难'] },
  { id: 'BP010', name: '声带', system: 'respiratory', relatedSymptoms: ['声音嘶哑', '咳嗽'] }
]

export const DEPARTMENTS: Department[] = [
  { id: 'DEP001', name: '呼吸内科', aliases: ['肺科', '呼吸科'], commonDiseases: ['肺炎', '慢性阻塞性肺疾病', '支气管哮喘', '肺结核', '肺结节', '肺癌'], description: '诊治呼吸系统疾病，包括肺部感染、慢性气道疾病、肺部肿瘤等' },
  { id: 'DEP002', name: '胸外科', aliases: ['心胸外科'], commonDiseases: ['肺癌', '肺结节', '气胸', '胸腔积液', '纵隔肿瘤'], description: '手术治疗胸部疾病，包括肺癌切除、肺结节切除、纵隔肿瘤切除等' },
  { id: 'DEP003', name: '肿瘤科', aliases: ['肿瘤内科', '化疗科'], commonDiseases: ['肺癌', '小细胞肺癌', '非小细胞肺癌', '肺腺癌', '肺鳞癌'], description: '诊治恶性肿瘤，包括化疗、靶向治疗、免疫治疗等' },
  { id: 'DEP004', name: '放疗科', aliases: ['放射治疗科'], commonDiseases: ['肺癌', '小细胞肺癌', '非小细胞肺癌'], description: '放射治疗恶性肿瘤' },
  { id: 'DEP005', name: '感染科', aliases: ['传染科'], commonDiseases: ['肺结核', '肺炎', '肺脓肿', '肺曲霉病', '肺隐球菌病'], description: '诊治感染性疾病，包括结核病、真菌感染等' },
  { id: 'DEP006', name: '急诊科', aliases: ['急诊'], commonDiseases: ['肺栓塞', '气胸', '重症肺炎', 'ARDS', '大咯血'], description: '急诊救治危重患者' },
  { id: 'DEP007', name: '重症医学科', aliases: ['ICU'], commonDiseases: ['ARDS', '呼吸衰竭', '重症肺炎', '肺栓塞'], description: '救治危重症患者' },
  { id: 'DEP008', name: '心血管内科', aliases: ['心内科'], commonDiseases: ['肺栓塞', '肺动脉高压', '肺心病'], description: '诊治心血管疾病' },
  { id: 'DEP009', name: '风湿免疫科', aliases: ['免疫科'], commonDiseases: ['间质性肺病', '肺纤维化', '自身免疫性疾病相关肺病'], description: '诊治风湿免疫性疾病' },
  { id: 'DEP010', name: '老年科', aliases: ['老年医学科'], commonDiseases: ['肺炎', '慢性阻塞性肺疾病', '吸入性肺炎', '肺结核'], description: '诊治老年患者疾病' }
]

export const RELATIONS: Relation[] = [
  { id: 'R001', type: 'HAS_SYMPTOM', sourceId: 'D001', sourceType: 'Disease', targetId: 'S001', targetType: 'Symptom', weight: 0.9 },
  { id: 'R002', type: 'HAS_SYMPTOM', sourceId: 'D001', sourceType: 'Disease', targetId: 'S004', targetType: 'Symptom', weight: 0.7 },
  { id: 'R003', type: 'HAS_SYMPTOM', sourceId: 'D001', sourceType: 'Disease', targetId: 'S002', targetType: 'Symptom', weight: 0.6 },
  { id: 'R004', type: 'HAS_SYMPTOM', sourceId: 'D002', sourceType: 'Disease', targetId: 'S001', targetType: 'Symptom', weight: 0.95 },
  { id: 'R005', type: 'HAS_SYMPTOM', sourceId: 'D002', sourceType: 'Disease', targetId: 'S002', targetType: 'Symptom', weight: 0.85 },
  { id: 'R006', type: 'HAS_SYMPTOM', sourceId: 'D002', sourceType: 'Disease', targetId: 'S004', targetType: 'Symptom', weight: 0.8 },
  { id: 'R007', type: 'HAS_SYMPTOM', sourceId: 'D002', sourceType: 'Disease', targetId: 'S003', targetType: 'Symptom', weight: 0.75 },
  { id: 'R008', type: 'HAS_SYMPTOM', sourceId: 'D002', sourceType: 'Disease', targetId: 'S011', targetType: 'Symptom', weight: 0.6 },
  { id: 'R009', type: 'HAS_SYMPTOM', sourceId: 'D003', sourceType: 'Disease', targetId: 'S005', targetType: 'Symptom', weight: 0.95 },
  { id: 'R010', type: 'HAS_SYMPTOM', sourceId: 'D003', sourceType: 'Disease', targetId: 'S001', targetType: 'Symptom', weight: 0.9 },
  { id: 'R011', type: 'HAS_SYMPTOM', sourceId: 'D003', sourceType: 'Disease', targetId: 'S006', targetType: 'Symptom', weight: 0.85 },
  { id: 'R012', type: 'HAS_SYMPTOM', sourceId: 'D004', sourceType: 'Disease', targetId: 'S001', targetType: 'Symptom', weight: 0.9 },
  { id: 'R013', type: 'HAS_SYMPTOM', sourceId: 'D004', sourceType: 'Disease', targetId: 'S003', targetType: 'Symptom', weight: 0.95 },
  { id: 'R014', type: 'HAS_SYMPTOM', sourceId: 'D004', sourceType: 'Disease', targetId: 'S006', targetType: 'Symptom', weight: 0.85 },
  { id: 'R015', type: 'HAS_SYMPTOM', sourceId: 'D005', sourceType: 'Disease', targetId: 'S007', targetType: 'Symptom', weight: 0.95 },
  { id: 'R016', type: 'HAS_SYMPTOM', sourceId: 'D005', sourceType: 'Disease', targetId: 'S003', targetType: 'Symptom', weight: 0.9 },
  { id: 'R017', type: 'HAS_SYMPTOM', sourceId: 'D005', sourceType: 'Disease', targetId: 'S001', targetType: 'Symptom', weight: 0.8 },
  { id: 'R018', type: 'HAS_SYMPTOM', sourceId: 'D006', sourceType: 'Disease', targetId: 'S001', targetType: 'Symptom', weight: 0.9 },
  { id: 'R019', type: 'HAS_SYMPTOM', sourceId: 'D006', sourceType: 'Disease', targetId: 'S002', targetType: 'Symptom', weight: 0.7 },
  { id: 'R020', type: 'HAS_SYMPTOM', sourceId: 'D006', sourceType: 'Disease', targetId: 'S005', targetType: 'Symptom', weight: 0.85 },
  { id: 'R021', type: 'HAS_SYMPTOM', sourceId: 'D006', sourceType: 'Disease', targetId: 'S010', targetType: 'Symptom', weight: 0.8 },
  { id: 'R022', type: 'TREATED_BY', sourceId: 'D002', sourceType: 'Disease', targetId: 'DR001', targetType: 'Drug', weight: 0.95 },
  { id: 'R023', type: 'TREATED_BY', sourceId: 'D002', sourceType: 'Disease', targetId: 'DR002', targetType: 'Drug', weight: 0.9 },
  { id: 'R024', type: 'TREATED_BY', sourceId: 'D002', sourceType: 'Disease', targetId: 'DR003', targetType: 'Drug', weight: 0.85 },
  { id: 'R025', type: 'TREATED_BY', sourceId: 'D002', sourceType: 'Disease', targetId: 'DR004', targetType: 'Drug', weight: 0.9 },
  { id: 'R026', type: 'TREATED_BY', sourceId: 'D002', sourceType: 'Disease', targetId: 'DR005', targetType: 'Drug', weight: 0.85 },
  { id: 'R027', type: 'TREATED_BY', sourceId: 'D002', sourceType: 'Disease', targetId: 'DR006', targetType: 'Drug', weight: 0.8 },
  { id: 'R028', type: 'TREATED_BY', sourceId: 'D002', sourceType: 'Disease', targetId: 'DR007', targetType: 'Drug', weight: 0.85 },
  { id: 'R029', type: 'TREATED_BY', sourceId: 'D003', sourceType: 'Disease', targetId: 'DR008', targetType: 'Drug', weight: 0.85 },
  { id: 'R030', type: 'TREATED_BY', sourceId: 'D003', sourceType: 'Disease', targetId: 'DR009', targetType: 'Drug', weight: 0.8 },
  { id: 'R031', type: 'TREATED_BY', sourceId: 'D003', sourceType: 'Disease', targetId: 'DR010', targetType: 'Drug', weight: 0.85 },
  { id: 'R032', type: 'TREATED_BY', sourceId: 'D004', sourceType: 'Disease', targetId: 'DR011', targetType: 'Drug', weight: 0.85 },
  { id: 'R033', type: 'TREATED_BY', sourceId: 'D004', sourceType: 'Disease', targetId: 'DR013', targetType: 'Drug', weight: 0.9 },
  { id: 'R034', type: 'TREATED_BY', sourceId: 'D004', sourceType: 'Disease', targetId: 'DR014', targetType: 'Drug', weight: 0.85 },
  { id: 'R035', type: 'TREATED_BY', sourceId: 'D005', sourceType: 'Disease', targetId: 'DR011', targetType: 'Drug', weight: 0.9 },
  { id: 'R036', type: 'TREATED_BY', sourceId: 'D005', sourceType: 'Disease', targetId: 'DR012', targetType: 'Drug', weight: 0.9 },
  { id: 'R037', type: 'TREATED_BY', sourceId: 'D005', sourceType: 'Disease', targetId: 'DR015', targetType: 'Drug', weight: 0.7 },
  { id: 'R038', type: 'TREATED_BY', sourceId: 'D006', sourceType: 'Disease', targetId: 'DR016', targetType: 'Drug', weight: 0.95 },
  { id: 'R039', type: 'TREATED_BY', sourceId: 'D006', sourceType: 'Disease', targetId: 'DR017', targetType: 'Drug', weight: 0.95 },
  { id: 'R040', type: 'TREATED_BY', sourceId: 'D006', sourceType: 'Disease', targetId: 'DR018', targetType: 'Drug', weight: 0.9 },
  { id: 'R041', type: 'TREATED_BY', sourceId: 'D006', sourceType: 'Disease', targetId: 'DR019', targetType: 'Drug', weight: 0.85 },
  { id: 'R042', type: 'TREATED_BY', sourceId: 'D007', sourceType: 'Disease', targetId: 'DR020', targetType: 'Drug', weight: 0.9 },
  { id: 'R043', type: 'TREATED_BY', sourceId: 'D007', sourceType: 'Disease', targetId: 'DR021', targetType: 'Drug', weight: 0.85 },
  { id: 'R044', type: 'TREATED_BY', sourceId: 'D009', sourceType: 'Disease', targetId: 'DR008', targetType: 'Drug', weight: 0.8 },
  { id: 'R045', type: 'TREATED_BY', sourceId: 'D009', sourceType: 'Disease', targetId: 'DR010', targetType: 'Drug', weight: 0.8 },
  { id: 'R046', type: 'TREATED_BY', sourceId: 'D021', sourceType: 'Disease', targetId: 'DR026', targetType: 'Drug', weight: 0.85 },
  { id: 'R047', type: 'TREATED_BY', sourceId: 'D021', sourceType: 'Disease', targetId: 'DR027', targetType: 'Drug', weight: 0.9 },
  { id: 'R048', type: 'TREATED_BY', sourceId: 'D021', sourceType: 'Disease', targetId: 'DR028', targetType: 'Drug', weight: 0.85 },
  { id: 'R049', type: 'TREATED_BY', sourceId: 'D022', sourceType: 'Disease', targetId: 'DR026', targetType: 'Drug', weight: 0.9 },
  { id: 'R050', type: 'TREATED_BY', sourceId: 'D022', sourceType: 'Disease', targetId: 'DR028', targetType: 'Drug', weight: 0.85 },
  { id: 'R051', type: 'NEEDS_EXAMINATION', sourceId: 'D001', sourceType: 'Disease', targetId: 'E001', targetType: 'Examination', weight: 0.95 },
  { id: 'R052', type: 'NEEDS_EXAMINATION', sourceId: 'D001', sourceType: 'Disease', targetId: 'E012', targetType: 'Examination', weight: 0.9 },
  { id: 'R053', type: 'NEEDS_EXAMINATION', sourceId: 'D002', sourceType: 'Disease', targetId: 'E001', targetType: 'Examination', weight: 0.95 },
  { id: 'R054', type: 'NEEDS_EXAMINATION', sourceId: 'D002', sourceType: 'Disease', targetId: 'E004', targetType: 'Examination', weight: 0.85 },
  { id: 'R055', type: 'NEEDS_EXAMINATION', sourceId: 'D002', sourceType: 'Disease', targetId: 'E006', targetType: 'Examination', weight: 0.7 },
  { id: 'R056', type: 'NEEDS_EXAMINATION', sourceId: 'D002', sourceType: 'Disease', targetId: 'E009', targetType: 'Examination', weight: 0.8 },
  { id: 'R057', type: 'NEEDS_EXAMINATION', sourceId: 'D002', sourceType: 'Disease', targetId: 'E010', targetType: 'Examination', weight: 0.85 },
  { id: 'R058', type: 'NEEDS_EXAMINATION', sourceId: 'D002', sourceType: 'Disease', targetId: 'E011', targetType: 'Examination', weight: 0.8 },
  { id: 'R059', type: 'NEEDS_EXAMINATION', sourceId: 'D003', sourceType: 'Disease', targetId: 'E002', targetType: 'Examination', weight: 0.9 },
  { id: 'R060', type: 'NEEDS_EXAMINATION', sourceId: 'D003', sourceType: 'Disease', targetId: 'E001', targetType: 'Examination', weight: 0.85 },
  { id: 'R061', type: 'NEEDS_EXAMINATION', sourceId: 'D003', sourceType: 'Disease', targetId: 'E005', targetType: 'Examination', weight: 0.9 },
  { id: 'R062', type: 'NEEDS_EXAMINATION', sourceId: 'D004', sourceType: 'Disease', targetId: 'E003', targetType: 'Examination', weight: 0.95 },
  { id: 'R063', type: 'NEEDS_EXAMINATION', sourceId: 'D004', sourceType: 'Disease', targetId: 'E002', targetType: 'Examination', weight: 0.8 },
  { id: 'R064', type: 'NEEDS_EXAMINATION', sourceId: 'D005', sourceType: 'Disease', targetId: 'E003', targetType: 'Examination', weight: 0.95 },
  { id: 'R065', type: 'NEEDS_EXAMINATION', sourceId: 'D006', sourceType: 'Disease', targetId: 'E001', targetType: 'Examination', weight: 0.9 },
  { id: 'R066', type: 'NEEDS_EXAMINATION', sourceId: 'D006', sourceType: 'Disease', targetId: 'E005', targetType: 'Examination', weight: 0.95 },
  { id: 'R067', type: 'NEEDS_EXAMINATION', sourceId: 'D007', sourceType: 'Disease', targetId: 'E001', targetType: 'Examination', weight: 0.9 },
  { id: 'R068', type: 'NEEDS_EXAMINATION', sourceId: 'D007', sourceType: 'Disease', targetId: 'E008', targetType: 'Examination', weight: 0.95 },
  { id: 'R069', type: 'NEEDS_EXAMINATION', sourceId: 'D007', sourceType: 'Disease', targetId: 'E007', targetType: 'Examination', weight: 0.85 },
  { id: 'R070', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D001', sourceType: 'Disease', targetId: 'DEP001', targetType: 'Department', weight: 1.0 },
  { id: 'R071', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D001', sourceType: 'Disease', targetId: 'DEP002', targetType: 'Department', weight: 0.9 },
  { id: 'R072', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D002', sourceType: 'Disease', targetId: 'DEP002', targetType: 'Department', weight: 1.0 },
  { id: 'R073', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D002', sourceType: 'Disease', targetId: 'DEP003', targetType: 'Department', weight: 0.95 },
  { id: 'R074', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D002', sourceType: 'Disease', targetId: 'DEP004', targetType: 'Department', weight: 0.85 },
  { id: 'R075', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D003', sourceType: 'Disease', targetId: 'DEP001', targetType: 'Department', weight: 1.0 },
  { id: 'R076', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D003', sourceType: 'Disease', targetId: 'DEP005', targetType: 'Department', weight: 0.8 },
  { id: 'R077', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D004', sourceType: 'Disease', targetId: 'DEP001', targetType: 'Department', weight: 1.0 },
  { id: 'R078', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D005', sourceType: 'Disease', targetId: 'DEP001', targetType: 'Department', weight: 1.0 },
  { id: 'R079', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D006', sourceType: 'Disease', targetId: 'DEP005', targetType: 'Department', weight: 1.0 },
  { id: 'R080', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D006', sourceType: 'Disease', targetId: 'DEP001', targetType: 'Department', weight: 0.9 },
  { id: 'R081', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D007', sourceType: 'Disease', targetId: 'DEP001', targetType: 'Department', weight: 0.9 },
  { id: 'R082', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D007', sourceType: 'Disease', targetId: 'DEP008', targetType: 'Department', weight: 0.9 },
  { id: 'R083', type: 'BELONGS_TO_DEPARTMENT', sourceId: 'D007', sourceType: 'Disease', targetId: 'DEP006', targetType: 'Department', weight: 0.95 },
  { id: 'R084', type: 'LOCATED_AT', sourceId: 'S001', sourceType: 'Symptom', targetId: 'BP001', targetType: 'BodyPart', weight: 0.95 },
  { id: 'R085', type: 'LOCATED_AT', sourceId: 'S001', sourceType: 'Symptom', targetId: 'BP002', targetType: 'BodyPart', weight: 0.9 },
  { id: 'R086', type: 'LOCATED_AT', sourceId: 'S002', sourceType: 'Symptom', targetId: 'BP001', targetType: 'BodyPart', weight: 0.95 },
  { id: 'R087', type: 'LOCATED_AT', sourceId: 'S002', sourceType: 'Symptom', targetId: 'BP002', targetType: 'BodyPart', weight: 0.85 },
  { id: 'R088', type: 'LOCATED_AT', sourceId: 'S003', sourceType: 'Symptom', targetId: 'BP001', targetType: 'BodyPart', weight: 0.9 },
  { id: 'R089', type: 'LOCATED_AT', sourceId: 'S004', sourceType: 'Symptom', targetId: 'BP001', targetType: 'BodyPart', weight: 0.85 },
  { id: 'R090', type: 'LOCATED_AT', sourceId: 'S004', sourceType: 'Symptom', targetId: 'BP004', targetType: 'BodyPart', weight: 0.9 },
  { id: 'R091', type: 'LOCATED_AT', sourceId: 'S007', sourceType: 'Symptom', targetId: 'BP002', targetType: 'BodyPart', weight: 0.95 },
  { id: 'R092', type: 'LOCATED_AT', sourceId: 'S011', sourceType: 'Symptom', targetId: 'BP009', targetType: 'BodyPart', weight: 0.95 },
  { id: 'R093', type: 'LOCATED_AT', sourceId: 'S011', sourceType: 'Symptom', targetId: 'BP010', targetType: 'BodyPart', weight: 0.95 },
  { id: 'R094', type: 'HAS_SIDE_EFFECT', sourceId: 'DR001', sourceType: 'Drug', targetId: 'S001', targetType: 'Symptom', weight: 0.6 },
  { id: 'R095', type: 'HAS_SIDE_EFFECT', sourceId: 'DR001', sourceType: 'Drug', targetId: 'S003', targetType: 'Symptom', weight: 0.3 },
  { id: 'R096', type: 'HAS_SIDE_EFFECT', sourceId: 'DR002', sourceType: 'Drug', targetId: 'S001', targetType: 'Symptom', weight: 0.7 },
  { id: 'R097', type: 'HAS_SIDE_EFFECT', sourceId: 'DR002', sourceType: 'Drug', targetId: 'S003', targetType: 'Symptom', weight: 0.2 },
  { id: 'R098', type: 'HAS_SIDE_EFFECT', sourceId: 'DR011', sourceType: 'Drug', targetId: 'S019', targetType: 'Symptom', weight: 0.5 },
  { id: 'R099', type: 'HAS_SIDE_EFFECT', sourceId: 'DR012', sourceType: 'Drug', targetId: 'S011', targetType: 'Symptom', weight: 0.4 },
  { id: 'R100', type: 'HAS_SIDE_EFFECT', sourceId: 'DR015', sourceType: 'Drug', targetId: 'S019', targetType: 'Symptom', weight: 0.6 }
]

export const KNOWLEDGE_GRAPH_DATA = {
  diseases: DISEASES,
  symptoms: SYMPTOMS,
  drugs: DRUGS,
  examinations: EXAMINATIONS,
  bodyParts: BODY_PARTS,
  departments: DEPARTMENTS,
  relations: RELATIONS
}

export default KNOWLEDGE_GRAPH_DATA
